import '../constant/phone_number_area.g.dart';
import 'core/validation_predicate.dart';

/// International fixed line number validation predicate.
/// Depends on code generated by tool/libphonenumber_generator.
///
/// {@template input_guide}
/// Expected input should be in the form: +<country code><phone number>.
/// Input should only contain plus sign [+] followed by country code and then
/// the number.
///
///   Examples: +12015550123 & +20452555555.
/// {@endtemplate}
abstract class FixedLineNumberValidationPredicate extends ValidationPredicate {
  const FixedLineNumberValidationPredicate({
    required this.fixedLineNumber,
  });

  final String fixedLineNumber;
}

/// International fixed line number validation predicate for some allowed areas.
///
/// Validating a valid number for an area that's not allowed will be
/// reported as invalid.
///
/// {@macro input_guide}
class SomeFixedLineNumberValidationPredicate
    extends FixedLineNumberValidationPredicate {
  const SomeFixedLineNumberValidationPredicate({
    required super.fixedLineNumber,
    required List<PhoneNumberArea> allowedAreas,
  }) : _allowedAreas = allowedAreas;

  final List<PhoneNumberArea> _allowedAreas;

  @override
  bool call() => _allowedAreas
      .map((e) => e.fixedLinePattern)
      .any((p) => p.hasMatch(fixedLineNumber));
}

/// International fixed line number validation predicate for all areas.
///
/// {@macro input_guide}
class AllFixedLineNumberValidationPredicate
    extends FixedLineNumberValidationPredicate {
  const AllFixedLineNumberValidationPredicate({
    required super.fixedLineNumber,
    List<PhoneNumberArea> forbiddenAreas = const [],
  }) : _forbiddenAreas = forbiddenAreas;

  final List<PhoneNumberArea> _forbiddenAreas;

  @override
  bool call() => PhoneNumberArea.values
      .where((e) => !_forbiddenAreas.contains(e))
      .map((e) => e.fixedLinePattern)
      .any((p) => p.hasMatch(fixedLineNumber));
}
