name: valid_forms
description: A simple form validation helper.
version: 0.7.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
