name: libphonenumber_generator
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  ansicolor: ^2.0.1
  args: ^2.3.1
  code_builder: ^4.3.0
  dart_style: ^2.2.4
  http: ^0.13.5
  xml2json: ^5.3.5

dev_dependencies:
  lints: ^2.0.0
